name: Build ImmortalWrt

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run build script
        run: |
          cd immortalwrt
          chmod +x build.sh docker-build.sh
          ./docker-build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-firmware
          path: immortalwrt/bin/*.img
